;;; color-theme-sgml.el --- color themes for sgml mode

;; $Id: color-theme-sgml.el,v 1.1.1.1 2007/04/20 13:10:58 rich Exp $

;; Copyright (C) 2001, Mark Johnson <mrj@debian.org>

;; Emacs Lisp Archive Entry
;; Filename: color-theme-sgml.el
;; Version: 0.7
;; Keywords: faces, sgml
;; Author: Mark Johnson <mrj@debian.org>
;; Maintainer: Mark Johnson <mrj@debian.org>
;; Description: color themes for psgml
;; Created: 25 March 2001
;; URL: http://dulug.duke.edu/~mark/emacs

;; This file is not part of GNU Emacs.

;; This is free software; you can redistribute it and/or modify it under
;; the terms of the GNU General Public License as published by the Free
;; Software Foundation; either version 2, or (at your option) any later
;; version.
;;
;; This is distributed in the hope that it will be useful, but WITHOUT
;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;; for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
;; MA 02111-1307, USA.

;;; Commentary:

;; This is a collection of themes for editing documents in sgml-mode.
;; It depends on the color-theme package.

;; Thanks to Holger Rauch <Holger.Rauch@heitec.de> for supplying the Black
;; themes.

;; Currently there are 9 themes:

;;    color-theme-sgml-light
;;    color-theme-sgml-blue-hi
;;    color-theme-sgml-blue-lo
;;    color-theme-sgml-green-hi
;;    color-theme-sgml-green-lo
;;    color-theme-sgml-black-hi
;;    color-theme-sgml-black-lo
;;    color-theme-sgml-black-hi-2
;;    color-theme-sgml-black-lo-2

;; To load a theme in your startup files,
;; add the following to the end of your .emacs

;; (require 'color-theme-sgml)
;; (color-theme-sgml-blue-lo)

;; Tested with Emacs 20.7 and Emacs 21.0


;;; History:
;; 
;; None, to speak of.


;;; Code:
(require 'color-theme)

(setq color-themes
      (append
       (list
	'(color-theme-sgml-light "Sgml Light" "Mark Johnson <mrj@debian.org>")
	'(color-theme-sgml-blue-hi "Sgml Blue High" "Mark Johnson <mrj@debian.org>")
	'(color-theme-sgml-blue-lo "Sgml Blue Low" "Mark Johnson <mrj@debian.org>")
	'(color-theme-sgml-green-hi "Sgml Green High" "Mark Johnson <mrj@debian.org>")
	'(color-theme-sgml-green-lo "Sgml Green Low" "Mark Johnson <mrj@debian.org>")
	'(color-theme-sgml-black-hi "Sgml Black High" "Holger Rauch <holger.rauch@heitec.de>")
	'(color-theme-sgml-black-lo "Sgml Black Low" "Holger Rauch <holger.rauch@heitec.de>")
	'(color-theme-sgml-black-hi-2 "Sgml Black High #2" "Holger Rauch <holger.rauch@heitec.de>")
	'(color-theme-sgml-black-lo-2 "Sgml Black Low #2" "Holger Rauch <holger.rauch@heitec.de>"))
       color-themes))





(defun color-theme-sgml-light ()
  "Black on light gray theme, based on standard Emacs theme.

Mainly for `sgml-mode', where it provides
syntax highlighting with boldface start tags."

  (interactive)
  (let ((color-theme-cumulative nil))
  (color-theme-install
   '(color-theme-sgml-light
     ((background-color . "gray95")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "red")
      (foreground-color . "black")
      (mouse-color . "gray95"))
     ((help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (tags-tag-face . default))
    (default ((t (:background "gray95" :foreground "black"))))
    (bold ((t (:bold (bold extra-bold ultra-bold) ))))
    (bold-italic ((t (:italic (italic oblique) :bold t))))
    (border ((t (:background "black" ))))
    (cursor ((t (:background "red"))))
    (CUA-mode-normal-cursor-color ((t (:background "red" ))))
    (dircolors-face-asm ((t (:foreground "Tan"))))
    (dircolors-face-backup ((t (:foreground "Magenta"))))
    (dircolors-face-compress ((t (:foreground "Sienna"))))
    (dircolors-face-dir ((t (:foreground "Blue"))))
    (dircolors-face-doc ((t (:foreground "DarkOrchid"))))
    (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
    (dircolors-face-emacs ((t (:foreground "OliveDrab"))))
    (dircolors-face-html ((t (:foreground "DarkCyan"))))
    (dircolors-face-img ((t (:foreground "Salmon"))))
    (dircolors-face-lang ((t (:foreground "DarkKhaki"))))
    (dircolors-face-lang-interface ((t (:foreground "DarkGoldenrod"))))
    (dircolors-face-make ((t (:foreground "DarkKhaki"))))
    (dircolors-face-objet ((t (:foreground "DimGray"))))
    (dircolors-face-package ((t (:foreground "IndianRed"))))
    (dircolors-face-paddb ((t (:foreground "Orange"))))
    (dircolors-face-ps ((t (:foreground "BlueViolet"))))
    (dircolors-face-sound ((t (:foreground "DarkSlateBlue"))))
    (dircolors-face-tar ((t (:foreground "OrangeRed"))))
    (dircolors-face-yacc ((t (:foreground "Coral"))))
    (font-lock-builtin-face ((t (:foreground "Orchid"))))
    (font-lock-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
    (font-lock-constant-face ((t (:foreground "CadetBlue"))))
    (font-lock-doc-face ((t (:foreground "rosybrown"))))
    (font-lock-function-name-face ((t (:bold t  :foreground "cyan4"))))
    (font-lock-keyword-face ((t (:foreground "firebrick"))))
    (font-lock-string-face ((t (:foreground "magenta"))))
    (font-lock-type-face ((t (:foreground "ForestGreen"))))
    (font-lock-variable-name-face ((t (:foreground "DarkGoldenrod4"))))
    (font-lock-warning-face ((t (:bold t :foreground "Red"))))
    (fringe ((t ( :background "gray95"))))
    (header-line ((t (:background "grey90" :foreground "grey20"))))
    (highlight ((t (:background "darkseagreen2" ))))
    (highlight-changes-delete-face ((t (:underline t :foreground "red"))))
    (highlight-changes-face ((t ( :foreground "red"))))
    (highline-face ((t (:background "paleturquoise"))))
    (info-header-node ((t (:bold t :foreground "brown"))))
    (info-header-xref ((t (:bold t  :foreground "brown"))))
    (info-menu-5 ((t (:bold t  :foreground "DarkMagenta"))))
    (info-menu-header ((t (:bold t :foreground "NavyBlue"))))
    (info-node ((t (:bold t :foreground "DarkGreen"))))
    (info-xref ((t (:bold t :foreground "DarkGreen"))))
    (isearch ((t (:inherit region))))
    (isearch-lazy-highlight-face ((t (:inherit secondary-selection))))
    (menu ((t (:background "gray87" :foreground "black" :box
        (:line-width 2 :color "gray87" :style released-button)
	 :slant normal :weight normal :height 1.0
         :width normal :family "adobe-helvetica"))))
    (mode-line ((t (:background "gray80" :foreground "black" :box
                (:line-width 2 :style released-button)
	       :slant normal :weight normal :height 1.0
               :width normal :family "adobe-helvetica"))))
    (modeline ((t (:background "gray80" :foreground "black"))))
    (modeline-buffer-id ((t (:background "gray80" :foreground "black"))))
    (modeline-mousable ((t (:background "gray80" :foreground "black"))))
    (modeline-mousable-minor-mode ((t (:background "gray80" :foreground "black"))))
    (mouse ((t (:foreground "gray95" :background "black" ))))
    (pointer ((t (nil))))
    (region ((t (:foreground "white" :background "SteelBlue3" ))))
    (scroll-bar ((t (:background "grey75"))))
    (secondary-selection ((t (:background "paleturquoise" ))))
    (sgml-comment-face ((t (:foreground "Gray60" :bold t :italic t))))
    (sgml-doctype-face ((t (:bold t :foreground "brown"))))
    (sgml-end-tag-face ((t (:bold t :foreground "green4"))))
    (sgml-entity-face ((t (:bold t :foreground "DarkOrchid1"))))
    (sgml-ignored-face ((t ( :foreground "Gray50"))))
    (sgml-ms-end-face ((t (:bold t :foreground "DeepPink"))))
    (sgml-ms-end-tag-face ((t (:bold t :foreground "DeepPink"))))
    (sgml-ms-start-face ((t ( :bold t :foreground "DeepPink" ))))
    (sgml-ms-start-tag-face ((t (:bold t :foreground "DeepPink"))))
    (sgml-pi-face ((t (:bold t :foreground "OrangeRed"))))
    (sgml-sgml-face ((t (:foreground "DarkGoldenRod"  ))))
    (sgml-short-ref-face ((t (:bold t :foreground "purple" ))))
    (sgml-start-tag-face ((t (:bold t :foreground "blue2"))))
    (show-paren-match-face ((t (:background "turquoise" ))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (tool-bar ((t (:background "gray87" ))))
    (trailing-whitespace ((t (:background "red" ))))
    (xsl-fo-alternate-face ((t (:foreground "plum4"))))
    (xsl-fo-main-face ((t (:bold t  :foreground "orchid4"))))
    (xsl-other-element-face ((t (:foreground "Blue"))))
    (xsl-xslt-alternate-face ((t (:foreground "DarkGreen"))))
    (xsl-xslt-main-face ((t (:foreground "red3"))))))))


(defun color-theme-sgml-blue-hi ()
  "High contrast gold on blue, based on the Jonadabian theme.

Mainly for `sgml-mode', where it provides
syntax highlighting with boldface start tags."

  (interactive)
  (let ((color-theme-cumulative nil))
  (color-theme-install
   '(color-theme-sgml-blue-hi
     ((background-color . "#000055")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "plum")
      (foreground-color . "#e2d588")
      (mouse-color . "gray80"))
     ((help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (sgml-set-face . t)
      (tags-tag-face . default)
      (view-highlight-face . highlight))
    (default ((t (:background "#000055" :foreground "#e2d588"))))
    (bold ((t (:bold t ))))
    (bold-italic ((t (:italic (italic oblique) :bold t))))
    (border ((t ( :background "black" ))))
    (cursor ((t (:background "plum" ))))
    (CUA-mode-normal-cursor-color ((t (:background "plum" ))))
    (dircolors-face-asm ((t ( :foreground "Tan"))))
    (dircolors-face-backup ((t (:foreground "Magenta"))))
    (dircolors-face-compress ((t (:foreground "LightPink2"))))
    (dircolors-face-dir ((t (:foreground "SkyBlue"))))
    (dircolors-face-doc ((t (:foreground "Orchid"))))
    (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
    (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
    (dircolors-face-html ((t (:foreground "YellowGreen"))))
    (dircolors-face-img ((t (:foreground "Salmon"))))
    (dircolors-face-lang ((t (:foreground "Khaki"))))
    (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
    (dircolors-face-make ((t (:foreground "Khaki"))))
    (dircolors-face-objet ((t (:foreground "DimGray"))))
    (dircolors-face-package ((t (:foreground "IndianRed1"))))
    (dircolors-face-paddb ((t (:foreground "Orange"))))
    (dircolors-face-ps ((t (:foreground "violet"))))
    (dircolors-face-sound ((t (:foreground "SlateGray1"))))
    (dircolors-face-tar ((t (:foreground "LightPink"))))
    (dircolors-face-yacc ((t (:foreground "Coral"))))
    (fixed-pitch ((t ())))
    (font-lock-builtin-face ((t (:bold t :foreground "PaleGreen"))))
    (font-lock-comment-face ((t (:italic t :bold t  :foreground "gray56"))))
    (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
    (font-lock-doc-face ((t ())))
    (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
    (font-lock-function-name-face ((t ( :foreground "cyan3"))))
    (font-lock-keyword-face ((t (:foreground "Salmon"))))
    (font-lock-reference-face ((t ( :foreground "pale green"))))
    (font-lock-string-face ((t ( :foreground "LightSalmon"))))
    (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
    (font-lock-variable-name-face ((t (:foreground "Aquamarine"))))
    (font-lock-warning-face ((t (:bold t  :foreground "red"))))
    (fringe ((t ( :background "#000055" ))))
    (header-line ((t (:background "grey20" :foreground "grey90"))))
    (highlight ((t (:background "#007080" :foreground "cyan"))))
    (highline-face ((t (:background "SeaGreen" ))))
    (info-header-node ((t (:bold t :foreground "Salmon"))))
    (info-header-xref ((t (:bold t :foreground "Salmon"))))
    (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
    (info-node ((t (:foreground "SeaGreen1"))))
    (info-xref ((t (:foreground "SeaGreen1"))))
    (isearch ((t ())))
    (isearch-lazy-highlight-face ((t ())))
    (italic ((t (:italic (italic oblique) ))))
    (menu ((t (:background "gray87" :foreground "black" :box
      (:line-width 2 :color "gray87" :style released-button)
       :slant normal :weight normal :height 1.0
       :width normal :family "adobe-helvetica"))))
    (mode-line ((t (:background "#007080" :foreground "cyan" :box
        (:line-width 2 :style released-button)
	 :slant normal :weight normal :height 1.0
         :width normal :family "adobe-helvetica"))))
    (modeline ((t (:background "#007080" :foreground "cyan"))))
    (modeline-buffer-id ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable-minor-mode ((t (:background "#007080" :foreground "cyan"))))
    (mouse ((t (:foreground "#000055" :background "gray80" ))))
    (pointer ((t (nil))))
    (region ((t (:background "dark cyan" :foreground "cyan"))))
    (scroll-bar ((t (:background "grey75"))))
    (secondary-selection ((t (:background "SkyBlue4" ))))
    (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
    (sgml-doctype-face ((t (:bold t :foreground "salmon"))))
    (sgml-end-tag-face ((t (:bold nil :foreground "SeaGreen3"))))
    (sgml-entity-face ((t (:bold t :foreground "plum2"))))
    (sgml-ignored-face ((t (:bold t :foreground "Gray50"))))
    (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-pi-face ((t (:bold t :foreground "lime green"))))
    (sgml-sgml-face ((t ())))
    (sgml-short-ref-face ((t ())))
    (sgml-start-tag-face ((t (:bold t :foreground "DeepSkyBlue1"))))
    (show-paren-match-face ((t (:background "turquoise" ))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (tool-bar ((t (:background "grey87" ))))
    (trailing-whitespace ((t (:background "red" ))))
    (underline ((t (:underline t ))))
    (variable-pitch ((t ())))
    (xsl-fo-alternate-face ((t (:foreground "SeaGreen3"))))
    (xsl-fo-main-face ((t (:foreground "DeepSkyBlue2"))))
    (xsl-other-element-face ((t (:foreground "burlywood2"))))
    (xsl-xslt-alternate-face ((t (:foreground "SeaGreen2"))))
    (xsl-xslt-main-face ((t (:foreground "LightSkyBlue"))))))))


(defun color-theme-sgml-blue-lo ()
  "Low contrast gold on blue, easy on the eyes.
Loosely based on the Jonadabian theme.

Mainly for `sgml-mode', where it provides
syntax highlighting with boldface start tags."

  (interactive)
  (let ((color-theme-cumulative nil))
  (color-theme-install
   '(color-theme-sgml-blue-lo
     ((background-color . "#2c2c51")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "plum")
      (foreground-color . "#c4ba89")
      (mouse-color . "gray80"))
     ((help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (sgml-set-face . t)
      (tags-tag-face . default)
      (view-highlight-face . highlight))
    (default ((t (:background "#2c2c51" :foreground "#c4ba89"))))
    (bold ((t (:bold t ))))
    (bold-italic ((t (:italic (italic oblique) :bold t))))
    (border ((t ( :background "black" ))))
    (cursor ((t (:background "plum" ))))
    (CUA-mode-normal-cursor-color ((t (:background "plum" ))))
    (dircolors-face-asm ((t ( :foreground "Tan"))))
    (dircolors-face-backup ((t (:foreground "Magenta"))))
    (dircolors-face-compress ((t (:foreground "LightPink2"))))
    (dircolors-face-dir ((t (:foreground "SkyBlue"))))
    (dircolors-face-doc ((t (:foreground "Orchid"))))
    (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
    (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
    (dircolors-face-html ((t (:foreground "YellowGreen"))))
    (dircolors-face-img ((t (:foreground "Salmon"))))
    (dircolors-face-lang ((t (:foreground "Khaki"))))
    (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
    (dircolors-face-make ((t (:foreground "Khaki"))))
    (dircolors-face-objet ((t (:foreground "DimGray"))))
    (dircolors-face-package ((t (:foreground "IndianRed1"))))
    (dircolors-face-paddb ((t (:foreground "Orange"))))
    (dircolors-face-ps ((t (:foreground "violet"))))
    (dircolors-face-sound ((t (:foreground "SlateGray1"))))
    (dircolors-face-tar ((t (:foreground "LightPink"))))
    (dircolors-face-yacc ((t (:foreground "Coral"))))
    (fixed-pitch ((t (nil))))
    (font-lock-builtin-face ((t (:bold t  :foreground "PaleGreen"))))
    (font-lock-comment-face ((t (:italic t :bold t  :foreground "gray56"))))
    (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
    (font-lock-doc-face ((t ())))
    (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
    (font-lock-function-name-face ((t ( :foreground "cyan3"))))
    (font-lock-keyword-face ((t (:foreground "Salmon"))))
    (font-lock-reference-face ((t ( :foreground "pale green"))))
    (font-lock-string-face ((t ( :foreground "LightSalmon"))))
    (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
    (font-lock-variable-name-face ((t (:foreground "Aquamarine"))))
    (font-lock-warning-face ((t (:bold t  :foreground "red"))))
    (fringe ((t ( :background "#2c2c51" ))))
    (header-line ((t (:background "grey20" :foreground "grey90"))))
    (highlight ((t (:background "#007080" :foreground "cyan"))))
    (info-header-node ((t (:bold t :foreground "Salmon"))))
    (info-header-xref ((t (:bold t :foreground "Salmon"))))
    (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
    (info-node ((t (:foreground "SeaGreen1"))))
    (info-xref ((t (:foreground "SeaGreen1"))))
    (isearch ((t ())))
    (isearch-lazy-highlight-face ((t ())))
    (italic ((t (:italic (italic oblique) ))))
    (menu ((t (:background "gray87" :foreground "black" :box
      (:line-width 2 :color "gray87" :style released-button)
       :slant normal :weight normal :height 1.0
       :width normal :family "adobe-helvetica"))))
    (mode-line ((t (:background "#007080" :foreground "cyan" :box
        (:line-width 2 :style released-button)
	 :slant normal :weight normal :height 1.0
         :width normal :family "adobe-helvetica"))))
    (modeline ((t (:background "#007080" :foreground "cyan"))))
    (modeline-buffer-id ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable-minor-mode ((t (:background "#007080" :foreground "cyan"))))
    (mouse ((t (:foreground "#2c2c51" :background "gray80"))))
    (pointer ((t (nil))))
    (region ((t (:background "dark cyan" :foreground "cyan"))))
    (scroll-bar ((t (:background "grey75"))))
    (secondary-selection ((t (:background "SkyBlue4" ))))
    (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
    (sgml-doctype-face ((t (:bold t :foreground "PaleVioletRed3"))))
    (sgml-start-tag-face ((t (:bold t :foreground "DeepSkyBlue3"))))
    (sgml-end-tag-face ((t (:bold nil :foreground "MediumSeaGreen"))))
    (sgml-entity-face ((t (:bold t  :foreground "plum3"))))
    (sgml-ignored-face ((t (:bold t :foreground "Gray50"))))
    (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-pi-face ((t (:bold t :foreground "SeaGreen3"))))
    (sgml-sgml-face ((t ())))
    (sgml-short-ref-face ((t ())))
    (show-paren-match-face ((t (:background "turquoise" ))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (tool-bar ((t (:background "grey87" ))))
    (trailing-whitespace ((t (:background "red" ))))
    (underline ((t (:underline t ))))
    (variable-pitch ((t ())))
    (xrdb-option-name-face ((t (:foreground "Aquamarine"))))
    (xrdb-option-value-face ((t ( :foreground "cyan3"))))
    (xsl-fo-alternate-face ((t (:foreground "SeaGreen3"))))
    (xsl-fo-main-face ((t (:foreground "DeepSkyBlue2"))))
    (xsl-other-element-face ((t (:foreground "burlywood2"))))
    (xsl-xslt-alternate-face ((t (:foreground "SeaGreen2"))))
    (xsl-xslt-main-face ((t (:foreground "LightSkyBlue"))))))))


 (defun color-theme-sgml-green-lo ()
  "Low contrast gold on green. Loosely based on the Gnome2 theme.

Mainly for `sgml-mode', where it provides
syntax highlighting with boldface start tags."

   (interactive)
  (let ((color-theme-cumulative nil))
   (color-theme-install
    '(color-theme-sgml-green-lo
      ((background-color . "#004147")
       (background-mode . dark)
       (border-color . "#004147")
       (cursor-color . "plum")
       (foreground-color . "wheat3")
       (mouse-color . "Grey"))
      ((help-highlight-face . underline)
       (list-matching-lines-face . bold)
       (sgml-set-face . t)
       (tags-tag-face . default))
     (default ((t (:background "#004147" :foreground "wheat3"))))
     (bold ((t (:bold t ))))
     (bold-italic ((t (:italic (italic oblique) :bold t :foreground "beige"))))
     (border ((t (:background "#004147" ))))
     (cursor ((t ( :background "plum" ))))
     (CUA-mode-normal-cursor-color ((t (:background "plum" ))))
     (dircolors-face-asm ((t ( :foreground "Tan"))))
     (dircolors-face-backup ((t (:foreground "Magenta"))))
     (dircolors-face-compress ((t (:foreground "LightPink2"))))
     (dircolors-face-dir ((t (:foreground "SkyBlue"))))
     (dircolors-face-doc ((t (:foreground "Orchid"))))
     (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
     (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
     (dircolors-face-html ((t (:foreground "YellowGreen"))))
     (dircolors-face-img ((t (:foreground "Salmon"))))
     (dircolors-face-lang ((t (:foreground "Khaki"))))
     (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
     (dircolors-face-make ((t (:foreground "Khaki"))))
     (dircolors-face-objet ((t (:foreground "DimGray"))))
     (dircolors-face-package ((t (:foreground "IndianRed1"))))
     (dircolors-face-paddb ((t (:foreground "Orange"))))
     (dircolors-face-ps ((t (:foreground "violet"))))
     (dircolors-face-sound ((t (:foreground "SlateGray1"))))
     (dircolors-face-tar ((t (:foreground "LightPink"))))
     (dircolors-face-yacc ((t (:foreground "Coral"))))
     (font-lock-builtin-face ((t (:bold t :foreground "PaleGreen"))))
     (font-lock-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
     (font-lock-doc-face ((t ())))
     (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
     (font-lock-function-name-face ((t (:foreground "cyan1"))))
     (font-lock-keyword-face ((t ( :foreground "Salmon"))))
     (font-lock-reference-face ((t ( :foreground "pale green"))))
     (font-lock-string-face ((t ( :foreground "LightSalmon"))))
     (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
     (font-lock-variable-name-face ((t ( :foreground "Aquamarine"))))
     (font-lock-warning-face ((t (:bold t :foreground "IndianRed"))))
     (fringe ((t (:background "#004147" ))))
     (header-line ((t (:background "grey20" :foreground "grey90"))))
     (highlight ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (highline-face ((t (:background "SeaGreen" ))))
     (info-header-node ((t (:bold t :foreground "Salmon"))))
     (info-header-xref ((t (:bold t :foreground "Salmon"))))
     (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
     (info-node ((t (:foreground "SeaGreen1"))))
     (info-xref ((t (:foreground "SeaGreen1"))))
     (isearch ((t (:background "sea green" t))))
     (isearch-lazy-highlight-face ((t ())))
     (italic ((t (:italic (italic oblique) :))))
     (menu ((t (:background "gray87" :foreground "black" :box
	   (:line-width 2 :color "gray87" :style released-button)
           :slant normal :weight normal :height 1.0
           :width normal :family "adobe-helvetica"))))
     (mode-line ((t (:background "aquamarine4" :foreground "Aquamarine" :box
	   (:line-width 2 :style released-button)
	    :slant normal :weight normal :height 1.0
            :width normal :family "adobe-helvetica"))))
     (modeline ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-buffer-id ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable-minor-mode ((t
            (:background "aquamarine4" :foreground "Aquamarine"))))
     (mouse ((t (:foreground "#004147" :background "Grey"))))
     (pointer ((t (nil))))
     (region ((t (:background "dark cyan" :foreground "cyan"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (sgml-doctype-face ((t (:bold t :foreground "PaleVioletRed3"))))
     (sgml-end-tag-face ((t (:bold nil  :foreground "MediumSeaGreen"))))
     (sgml-entity-face ((t (:bold t  :foreground "plum3"))))
     (sgml-ignored-face ((t (:bold t  :foreground "Gray50"))))
     (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1" ))))
     (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-tag-face ((t (:bold t  :foreground "MediumPurple1"))))
     (sgml-pi-face ((t (:bold t :foreground "SeaGreen3"))))
     (sgml-sgml-face ((t ())))
     (sgml-short-ref-face ((t ())))
     (sgml-start-tag-face ((t (:bold t  :foreground "DeepSkyBlue3"))))
     (show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (tool-bar ((t (:background "grey87"))))
     (trailing-whitespace ((t (:background "red" ))))
     (underline ((t (:underline t ))))
     (variable-pitch ((t ())))
     (xsl-fo-main-face ((t ( :foreground "LightSkyBlue"))))
     (xsl-other-element-face ((t ( :foreground "burlywood2"))))
     (xsl-xslt-alternate-face ((t ( :foreground "SeaGreen2"))))
     (xsl-xslt-main-face ((t ( :foreground "LightSkyBlue"))))))))


 (defun color-theme-sgml-green-hi ()
  "Gold on green, based on the Gnome2 theme.

Mainly for `sgml-mode', where it provides
syntax highlighting with boldface start tags."

   (interactive)
  (let ((color-theme-cumulative nil))
   (color-theme-install
    '(color-theme-sgml-green-hi
      ((background-color . "#004147")
       (background-mode . dark)
       (border-color . "#004147")
       (cursor-color . "plum")
       (foreground-color . "wheat2")
       (mouse-color . "Grey"))
      ((help-highlight-face . underline)
       (list-matching-lines-face . bold)
       (sgml-set-face . t)
       (tags-tag-face . default))
     (default ((t (:background "#004147" :foreground "wheat2"))))
     (bold ((t (:bold t ))))
     (bold-italic ((t (:italic (italic oblique) :bold t :foreground "beige"))))
     (border ((t (:background "#004147" ))))
     (cursor ((t ( :background "plum" ))))
     (CUA-mode-normal-cursor-color ((t (:background "plum" ))))
     (dircolors-face-asm ((t ( :foreground "Tan"))))
     (dircolors-face-backup ((t (:foreground "Magenta"))))
     (dircolors-face-compress ((t (:foreground "LightPink2"))))
     (dircolors-face-dir ((t (:foreground "SkyBlue"))))
     (dircolors-face-doc ((t (:foreground "Orchid"))))
     (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
     (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
     (dircolors-face-html ((t (:foreground "YellowGreen"))))
     (dircolors-face-img ((t (:foreground "Salmon"))))
     (dircolors-face-lang ((t (:foreground "Khaki"))))
     (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
     (dircolors-face-make ((t (:foreground "Khaki"))))
     (dircolors-face-objet ((t (:foreground "DimGray"))))
     (dircolors-face-package ((t (:foreground "IndianRed1"))))
     (dircolors-face-paddb ((t (:foreground "Orange"))))
     (dircolors-face-ps ((t (:foreground "violet"))))
     (dircolors-face-sound ((t (:foreground "SlateGray1"))))
     (dircolors-face-tar ((t (:foreground "LightPink"))))
     (dircolors-face-yacc ((t (:foreground "Coral"))))
     (font-lock-builtin-face ((t (:bold t :foreground "PaleGreen"))))
     (font-lock-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
     (font-lock-doc-face ((t ())))
     (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
     (font-lock-function-name-face ((t (:foreground "cyan1"))))
     (font-lock-keyword-face ((t ( :foreground "Salmon"))))
     (font-lock-reference-face ((t ( :foreground "pale green"))))
     (font-lock-string-face ((t ( :foreground "LightSalmon"))))
     (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
     (font-lock-variable-name-face ((t ( :foreground "Aquamarine"))))
     (font-lock-warning-face ((t (:bold t :foreground "IndianRed"))))
     (fringe ((t (:background "#004147" ))))
     (header-line ((t (:background "grey20" :foreground "grey90"))))
     (highlight ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (highline-face ((t (:background "SeaGreen" ))))
     (info-header-node ((t (:bold t :foreground "Salmon"))))
     (info-header-xref ((t (:bold t :foreground "Salmon"))))
     (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
     (info-node ((t (:foreground "SeaGreen1"))))
     (info-xref ((t (:foreground "SeaGreen1"))))
     (isearch ((t (:background "sea green" t))))
     (isearch-lazy-highlight-face ((t ())))
     (italic ((t (:italic (italic oblique) :))))
     (menu ((t (:background "gray87" :foreground "black" :box
	   (:line-width 2 :color "gray87" :style released-button)
           :slant normal :weight normal :height 1.0
           :width normal :family "adobe-helvetica"))))
     (mode-line ((t (:background "aquamarine4" :foreground "Aquamarine" :box
	   (:line-width 2 :style released-button)
	    :slant normal :weight normal :height 1.0
            :width normal :family "adobe-helvetica"))))
     (modeline ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-buffer-id ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable-minor-mode ((t
            (:background "aquamarine4" :foreground "Aquamarine"))))
     (mouse ((t (:foreground: "#004147" :background "Grey" ))))
     (pointer ((t (nil))))
     (region ((t (:background "dark cyan" :foreground "cyan"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (sgml-doctype-face ((t (:bold t :foreground "salmon"))))
     (sgml-end-tag-face ((t (:bold nil  :foreground "SeaGreen3"))))
     (sgml-entity-face ((t (:bold t  :foreground "plum2"))))
     (sgml-ignored-face ((t (:bold t  :foreground "Gray50"))))
     (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1" ))))
     (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-tag-face ((t (:bold t  :foreground "MediumPurple1"))))
     (sgml-pi-face ((t (:bold t :foreground "lime green"))))
     (sgml-sgml-face ((t ())))
     (sgml-short-ref-face ((t ())))
     (sgml-start-tag-face ((t (:bold t  :foreground "DeepSkyBlue2"))))
     (show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (tool-bar ((t (:background "grey87" ))))
     (trailing-whitespace ((t (:background "red" ))))
     (underline ((t (:underline t ))))
     (variable-pitch ((t ())))
     (xsl-fo-main-face ((t ( :foreground "LightSkyBlue"))))
     (xsl-other-element-face ((t ( :foreground "burlywood2"))))
     (xsl-xslt-alternate-face ((t ( :foreground "SeaGreen2"))))
     (xsl-xslt-main-face ((t ( :foreground "LightSkyBlue"))))))))


(defun color-theme-sgml-black-hi ()
  "High contrast gray on black, based on the blue-hi theme.

Mainly for `sgml-mode', where it provides
syntax highlighting with boldface tags."

  (interactive)
  (let ((color-theme-cumulative nil))
  (color-theme-install
   '(color-theme-sgml-black-hi
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "cyan")
      (foreground-color . "gray")
      (mouse-color . "cyan"))
     ((help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (sgml-set-face . t)
      (tags-tag-face . default)
      (view-highlight-face . highlight))
    (default ((t (:background "black" :foreground "gray"))))
    (bold ((t (:bold t ))))
    (bold-italic ((t (:italic (italic oblique) :bold t))))
    (border ((t ( :background "black" ))))
    (cursor ((t (:background "cyan" ))))
    (CUA-mode-normal-cursor-color ((t (:background "cyan" ))))
    (dircolors-face-asm ((t ( :foreground "Tan"))))
    (dircolors-face-backup ((t (:foreground "Magenta"))))
    (dircolors-face-compress ((t (:foreground "LightPink2"))))
    (dircolors-face-dir ((t (:foreground "SkyBlue"))))
    (dircolors-face-doc ((t (:foreground "Orchid"))))
    (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
    (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
    (dircolors-face-html ((t (:foreground "YellowGreen"))))
    (dircolors-face-img ((t (:foreground "Salmon"))))
    (dircolors-face-lang ((t (:foreground "Khaki"))))
    (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
    (dircolors-face-make ((t (:foreground "Khaki"))))
    (dircolors-face-objet ((t (:foreground "DimGray"))))
    (dircolors-face-package ((t (:foreground "IndianRed1"))))
    (dircolors-face-paddb ((t (:foreground "Orange"))))
    (dircolors-face-ps ((t (:foreground "violet"))))
    (dircolors-face-sound ((t (:foreground "SlateGray1"))))
    (dircolors-face-tar ((t (:foreground "LightPink"))))
    (dircolors-face-yacc ((t (:foreground "Coral"))))
    (fixed-pitch ((t ())))
    (font-lock-builtin-face ((t (:bold t :foreground "PaleGreen"))))
    (font-lock-comment-face ((t (:italic t :bold t  :foreground "gray56"))))
    (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
    (font-lock-doc-face ((t ())))
    (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
    (font-lock-function-name-face ((t ( :foreground "cyan3"))))
    (font-lock-keyword-face ((t (:foreground "Salmon"))))
    (font-lock-reference-face ((t ( :foreground "pale green"))))
    (font-lock-string-face ((t ( :foreground "LightSalmon"))))
    (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
    (font-lock-variable-name-face ((t (:foreground "Aquamarine"))))
    (font-lock-warning-face ((t (:bold t  :foreground "red"))))
    (fringe ((t ( :background "black" ))))
    (header-line ((t (:background "grey20" :foreground "grey90"))))
    (highlight ((t (:background "PaleGreen" :foreground "DarkGreen"))))
    (highline-face ((t (:background "SeaGreen" ))))
    (info-header-node ((t (:bold t :foreground "Salmon"))))
    (info-header-xref ((t (:bold t :foreground "Salmon"))))
    (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
    (info-node ((t (:foreground "SeaGreen1"))))
    (info-xref ((t (:foreground "SeaGreen1"))))
    (isearch ((t ())))
    (isearch-lazy-highlight-face ((t ())))
    (italic ((t (:italic (italic oblique) ))))
    (menu ((t (:background "gray87" :foreground "black" :box
      (:line-width 2 :color "gray87" :style released-button)
       :slant normal :weight normal :height 1.0
       :width normal :family "adobe-helvetica"))))
    (mode-line ((t (:background "#007080" :foreground "cyan" :box
        (:line-width 2 :style released-button)
	 :slant normal :weight normal :height 1.0
         :width normal :family "adobe-helvetica"))))
    (modeline ((t (:background "#007080" :foreground "cyan"))))
    (modeline-buffer-id ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable-minor-mode ((t (:background "#007080" :foreground "cyan"))))
    (mouse ((t (:foreground "black" :background "gray80" ))))
    (pointer ((t (nil))))
    (region ((t (:background "dark cyan" :foreground "cyan"))))
    (scroll-bar ((t (:background "grey75"))))
    (secondary-selection ((t (:background "SkyBlue4" ))))
    (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
    (sgml-doctype-face ((t (:bold t :foreground "salmon"))))
    (sgml-end-tag-face ((t (:bold t :foreground "DeepSkyBlue1"))))
    (sgml-entity-face ((t (:bold t :foreground "plum2"))))
    (sgml-ignored-face ((t (:bold t :foreground "Gray50"))))
    (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-pi-face ((t (:bold t :foreground "lime green"))))
    (sgml-sgml-face ((t ())))
    (sgml-short-ref-face ((t ())))
    (sgml-start-tag-face ((t (:bold t :foreground "DeepSkyBlue1"))))
    (show-paren-match-face ((t (:background "turquoise" ))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (tool-bar ((t (:background "grey87" ))))
    (trailing-whitespace ((t (:background "red" ))))
    (underline ((t (:underline t ))))
    (variable-pitch ((t ())))
    (xsl-fo-alternate-face ((t (:foreground "SeaGreen3"))))
    (xsl-fo-main-face ((t (:foreground "DeepSkyBlue2"))))
    (xsl-other-element-face ((t (:foreground "burlywood2"))))
    (xsl-xslt-alternate-face ((t (:foreground "SeaGreen2"))))
    (xsl-xslt-main-face ((t (:foreground "LightSkyBlue"))))))))


(defun color-theme-sgml-black-lo ()
  "Low contrast gray on black, easy on the eyes.
Based on the blue-lo theme.

Mainly for `sgml-mode', where it provides
syntax highlighting with boldface tags."

  (interactive)
  (let ((color-theme-cumulative nil))
  (color-theme-install
   '(color-theme-sgml-black-lo
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "cyan")
      (foreground-color . "gray")
      (mouse-color . "cyan"))
     ((help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (sgml-set-face . t)
      (tags-tag-face . default)
      (view-highlight-face . highlight))
    (default ((t (:background "black" :foreground "gray"))))
    (bold ((t (:bold t ))))
    (bold-italic ((t (:italic (italic oblique) :bold t))))
    (border ((t ( :background "black" ))))
    (cursor ((t (:background "cyan" ))))
    (CUA-mode-normal-cursor-color ((t (:background "cyan" ))))
    (dircolors-face-asm ((t ( :foreground "Tan"))))
    (dircolors-face-backup ((t (:foreground "Magenta"))))
    (dircolors-face-compress ((t (:foreground "LightPink2"))))
    (dircolors-face-dir ((t (:foreground "SkyBlue"))))
    (dircolors-face-doc ((t (:foreground "Orchid"))))
    (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
    (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
    (dircolors-face-html ((t (:foreground "YellowGreen"))))
    (dircolors-face-img ((t (:foreground "Salmon"))))
    (dircolors-face-lang ((t (:foreground "Khaki"))))
    (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
    (dircolors-face-make ((t (:foreground "Khaki"))))
    (dircolors-face-objet ((t (:foreground "DimGray"))))
    (dircolors-face-package ((t (:foreground "IndianRed1"))))
    (dircolors-face-paddb ((t (:foreground "Orange"))))
    (dircolors-face-ps ((t (:foreground "violet"))))
    (dircolors-face-sound ((t (:foreground "SlateGray1"))))
    (dircolors-face-tar ((t (:foreground "LightPink"))))
    (dircolors-face-yacc ((t (:foreground "Coral"))))
    (fixed-pitch ((t (nil))))
    (font-lock-builtin-face ((t (:bold t  :foreground "PaleGreen"))))
    (font-lock-comment-face ((t (:italic t :bold t  :foreground "gray56"))))
    (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
    (font-lock-doc-face ((t ())))
    (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
    (font-lock-function-name-face ((t ( :foreground "cyan3"))))
    (font-lock-keyword-face ((t (:foreground "Salmon"))))
    (font-lock-reference-face ((t ( :foreground "pale green"))))
    (font-lock-string-face ((t ( :foreground "LightSalmon"))))
    (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
    (font-lock-variable-name-face ((t (:foreground "Aquamarine"))))
    (font-lock-warning-face ((t (:bold t  :foreground "red"))))
    (fringe ((t ( :background "black" ))))
    (header-line ((t (:background "grey20" :foreground "grey90"))))
    (info-header-node ((t (:bold t :foreground "Salmon"))))
    (info-header-xref ((t (:bold t :foreground "Salmon"))))
    (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
    (info-node ((t (:foreground "SeaGreen1"))))
    (info-xref ((t (:foreground "SeaGreen1"))))
    (isearch ((t ())))
    (isearch-lazy-highlight-face ((t ())))
    (italic ((t (:italic (italic oblique) ))))
    (menu ((t (:background "gray87" :foreground "black" :box
      (:line-width 2 :color "gray87" :style released-button)
       :slant normal :weight normal :height 1.0
       :width normal :family "adobe-helvetica"))))
    (mode-line ((t (:background "#007080" :foreground "cyan" :box
        (:line-width 2 :style released-button)
	 :slant normal :weight normal :height 1.0
         :width normal :family "adobe-helvetica"))))
    (modeline ((t (:background "#007080" :foreground "cyan"))))
    (modeline-buffer-id ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable ((t (:background "#007080" :foreground "cyan"))))
    (modeline-mousable-minor-mode ((t (:background "#007080" :foreground "cyan"))))
    (mouse ((t (:foreground "black" :background "gray80"))))
    (pointer ((t (nil))))
    (region ((t (:background "dark cyan" :foreground "cyan"))))
    (scroll-bar ((t (:background "grey75"))))
    (secondary-selection ((t (:background "SkyBlue4" ))))
    (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
    (sgml-doctype-face ((t (:bold t :foreground "PaleVioletRed3"))))
    (sgml-start-tag-face ((t (:bold t :foreground "DeepSkyBlue3"))))
    (sgml-end-tag-face ((t (:bold t  :foreground "DeepSkyBlue3"))))
    (sgml-entity-face ((t (:bold t  :foreground "plum3"))))
    (sgml-ignored-face ((t (:bold t :foreground "Gray50"))))
    (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-ms-start-tag-face ((t (:bold t :foreground "MediumPurple1"))))
    (sgml-pi-face ((t (:bold t :foreground "SeaGreen3"))))
    (sgml-sgml-face ((t ())))
    (sgml-short-ref-face ((t ())))
    (show-paren-match-face ((t (:background "turquoise" ))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (tool-bar ((t (:background "grey87" ))))
    (trailing-whitespace ((t (:background "red" ))))
    (underline ((t (:underline t ))))
    (variable-pitch ((t ())))
    (xrdb-option-name-face ((t (:foreground "Aquamarine"))))
    (xrdb-option-value-face ((t ( :foreground "cyan3"))))
    (xsl-fo-alternate-face ((t (:foreground "SeaGreen3"))))
    (xsl-fo-main-face ((t (:foreground "DeepSkyBlue2"))))
    (xsl-other-element-face ((t (:foreground "burlywood2"))))
    (xsl-xslt-alternate-face ((t (:foreground "SeaGreen2"))))
    (xsl-xslt-main-face ((t (:foreground "LightSkyBlue"))))))))


 (defun color-theme-sgml-black-lo-2 ()
  "Low contrast gold on black. Loosely based on the Gnome2 theme.

Mainly for sgml-mode, where it provides
syntax highlighting with boldface tags."

   (interactive)
  (let ((color-theme-cumulative nil))
   (color-theme-install
    '(color-theme-sgml-black-lo-2
      ((background-color . "black")
       (background-mode . dark)
       (border-color . "black")
       (cursor-color . "cyan")
       (foreground-color . "gray")
       (mouse-color . "cyan"))
      ((help-highlight-face . underline)
       (list-matching-lines-face . bold)
       (sgml-set-face . t)
       (tags-tag-face . default))
     (default ((t (:background "black" :foreground "gray"))))
     (bold ((t (:bold t ))))
     (bold-italic ((t (:italic (italic oblique) :bold t :foreground "beige"))))
     (border ((t (:background "black" ))))
     (cursor ((t ( :background "cyan" ))))
     (CUA-mode-normal-cursor-color ((t (:background "cyan" ))))
     (dircolors-face-asm ((t ( :foreground "Tan"))))
     (dircolors-face-backup ((t (:foreground "Magenta"))))
     (dircolors-face-compress ((t (:foreground "LightPink2"))))
     (dircolors-face-dir ((t (:foreground "SkyBlue"))))
     (dircolors-face-doc ((t (:foreground "Orchid"))))
     (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
     (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
     (dircolors-face-html ((t (:foreground "YellowGreen"))))
     (dircolors-face-img ((t (:foreground "Salmon"))))
     (dircolors-face-lang ((t (:foreground "Khaki"))))
     (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
     (dircolors-face-make ((t (:foreground "Khaki"))))
     (dircolors-face-objet ((t (:foreground "DimGray"))))
     (dircolors-face-package ((t (:foreground "IndianRed1"))))
     (dircolors-face-paddb ((t (:foreground "Orange"))))
     (dircolors-face-ps ((t (:foreground "violet"))))
     (dircolors-face-sound ((t (:foreground "SlateGray1"))))
     (dircolors-face-tar ((t (:foreground "LightPink"))))
     (dircolors-face-yacc ((t (:foreground "Coral"))))
     (font-lock-builtin-face ((t (:bold t :foreground "PaleGreen"))))
     (font-lock-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
     (font-lock-doc-face ((t ())))
     (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
     (font-lock-function-name-face ((t (:foreground "cyan1"))))
     (font-lock-keyword-face ((t ( :foreground "Salmon"))))
     (font-lock-reference-face ((t ( :foreground "pale green"))))
     (font-lock-string-face ((t ( :foreground "LightSalmon"))))
     (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
     (font-lock-variable-name-face ((t ( :foreground "Aquamarine"))))
     (font-lock-warning-face ((t (:bold t :foreground "IndianRed"))))
     (fringe ((t (:background "black" ))))
     (header-line ((t (:background "grey20" :foreground "grey90"))))
     (highlight ((t (:background "PaleGreen" :foreground "DarkGreen"))))
     (highline-face ((t (:background "SeaGreen" ))))
     (info-header-node ((t (:bold t :foreground "Salmon"))))
     (info-header-xref ((t (:bold t :foreground "Salmon"))))
     (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
     (info-node ((t (:foreground "SeaGreen1"))))
     (info-xref ((t (:foreground "SeaGreen1"))))
     (isearch ((t (:background "sea green" t))))
     (isearch-lazy-highlight-face ((t ())))
     (italic ((t (:italic (italic oblique) :))))
     (menu ((t (:background "gray87" :foreground "black" :box
	   (:line-width 2 :color "gray87" :style released-button)
           :slant normal :weight normal :height 1.0
           :width normal :family "adobe-helvetica"))))
     (mode-line ((t (:background "aquamarine4" :foreground "Aquamarine" :box
	   (:line-width 2 :style released-button)
	    :slant normal :weight normal :height 1.0
            :width normal :family "adobe-helvetica"))))
     (modeline ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-buffer-id ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable-minor-mode ((t
            (:background "aquamarine4" :foreground "Aquamarine"))))
     (mouse ((t (:foreground "black" :background "Grey"))))
     (pointer ((t (nil))))
     (region ((t (:background "dark cyan" :foreground "cyan"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (sgml-doctype-face ((t (:bold t :foreground "PaleVioletRed3"))))
     (sgml-end-tag-face ((t (:bold t  :foreground "DeepSkyBlue3"))))
     (sgml-entity-face ((t (:bold t  :foreground "plum3"))))
     (sgml-ignored-face ((t (:bold t  :foreground "Gray50"))))
     (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1" ))))
     (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-tag-face ((t (:bold t  :foreground "MediumPurple1"))))
     (sgml-pi-face ((t (:bold t :foreground "SeaGreen3"))))
     (sgml-sgml-face ((t ())))
     (sgml-short-ref-face ((t ())))
     (sgml-start-tag-face ((t (:bold t  :foreground "DeepSkyBlue3"))))
     (show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (tool-bar ((t (:background "grey87"))))
     (trailing-whitespace ((t (:background "red" ))))
     (underline ((t (:underline t ))))
     (variable-pitch ((t ())))
     (xsl-fo-main-face ((t ( :foreground "LightSkyBlue"))))
     (xsl-other-element-face ((t ( :foreground "burlywood2"))))
     (xsl-xslt-alternate-face ((t ( :foreground "SeaGreen2"))))
     (xsl-xslt-main-face ((t ( :foreground "LightSkyBlue"))))))))


 (defun color-theme-sgml-black-hi-2 ()
  "Gold on black, based on the Gnome2 theme.

Mainly for sgml-mode, where it provides
syntax highlighting with boldface tags."

   (interactive)
  (let ((color-theme-cumulative nil))
   (color-theme-install
    '(color-theme-sgml-black-hi-2
      ((background-color . "black")
       (background-mode . dark)
       (border-color . "black")
       (cursor-color . "cyan")
       (foreground-color . "gray")
       (mouse-color . "cyan"))
      ((help-highlight-face . underline)
       (list-matching-lines-face . bold)
       (sgml-set-face . t)
       (tags-tag-face . default))
     (default ((t (:background "black" :foreground "gray"))))
     (bold ((t (:bold t ))))
     (bold-italic ((t (:italic (italic oblique) :bold t :foreground "beige"))))
     (border ((t (:background "black" ))))
     (cursor ((t ( :background "cyan" ))))
     (CUA-mode-normal-cursor-color ((t (:background "cyan" ))))
     (dircolors-face-asm ((t ( :foreground "Tan"))))
     (dircolors-face-backup ((t (:foreground "Magenta"))))
     (dircolors-face-compress ((t (:foreground "LightPink2"))))
     (dircolors-face-dir ((t (:foreground "SkyBlue"))))
     (dircolors-face-doc ((t (:foreground "Orchid"))))
     (dircolors-face-dos ((t (:foreground "MediumSeaGreen"))))
     (dircolors-face-emacs ((t (:foreground "LimeGreen"))))
     (dircolors-face-html ((t (:foreground "YellowGreen"))))
     (dircolors-face-img ((t (:foreground "Salmon"))))
     (dircolors-face-lang ((t (:foreground "Khaki"))))
     (dircolors-face-lang-interface ((t (:foreground "Goldenrod"))))
     (dircolors-face-make ((t (:foreground "Khaki"))))
     (dircolors-face-objet ((t (:foreground "DimGray"))))
     (dircolors-face-package ((t (:foreground "IndianRed1"))))
     (dircolors-face-paddb ((t (:foreground "Orange"))))
     (dircolors-face-ps ((t (:foreground "violet"))))
     (dircolors-face-sound ((t (:foreground "SlateGray1"))))
     (dircolors-face-tar ((t (:foreground "LightPink"))))
     (dircolors-face-yacc ((t (:foreground "Coral"))))
     (font-lock-builtin-face ((t (:bold t :foreground "PaleGreen"))))
     (font-lock-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (font-lock-constant-face ((t (:foreground "LightSteelBlue1"))))
     (font-lock-doc-face ((t ())))
     (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
     (font-lock-function-name-face ((t (:foreground "cyan1"))))
     (font-lock-keyword-face ((t ( :foreground "Salmon"))))
     (font-lock-reference-face ((t ( :foreground "pale green"))))
     (font-lock-string-face ((t ( :foreground "LightSalmon"))))
     (font-lock-type-face ((t (:bold t  :foreground "YellowGreen"))))
     (font-lock-variable-name-face ((t ( :foreground "Aquamarine"))))
     (font-lock-warning-face ((t (:bold t :foreground "IndianRed"))))
     (fringe ((t (:background "black" ))))
     (header-line ((t (:background "grey20" :foreground "grey90"))))
     (highlight ((t (:background "PaleGreen" :foreground "DarkGreen"))))
     (highline-face ((t (:background "SeaGreen" ))))
     (info-header-node ((t (:bold t :foreground "Salmon"))))
     (info-header-xref ((t (:bold t :foreground "Salmon"))))
     (info-menu-header ((t (:bold t :foreground "DeepSkyBlue"))))
     (info-node ((t (:foreground "SeaGreen1"))))
     (info-xref ((t (:foreground "SeaGreen1"))))
     (isearch ((t (:background "sea green" t))))
     (isearch-lazy-highlight-face ((t ())))
     (italic ((t (:italic (italic oblique) :))))
     (menu ((t (:background "gray87" :foreground "black" :box
	   (:line-width 2 :color "gray87" :style released-button)
           :slant normal :weight normal :height 1.0
           :width normal :family "adobe-helvetica"))))
     (mode-line ((t (:background "aquamarine4" :foreground "Aquamarine" :box
	   (:line-width 2 :style released-button)
	    :slant normal :weight normal :height 1.0
            :width normal :family "adobe-helvetica"))))
     (modeline ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-buffer-id ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable ((t (:background "aquamarine4" :foreground "Aquamarine"))))
     (modeline-mousable-minor-mode ((t
            (:background "aquamarine4" :foreground "Aquamarine"))))
     (mouse ((t (:foreground: "black" :background "Grey" ))))
     (pointer ((t (nil))))
     (region ((t (:background "dark cyan" :foreground "cyan"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (sgml-comment-face ((t (:bold t :italic t :foreground "Gray60"))))
     (sgml-doctype-face ((t (:bold t :foreground "salmon"))))
     (sgml-end-tag-face ((t (:bold t  :foreground "DeepSkyBlue2"))))
     (sgml-entity-face ((t (:bold t  :foreground "plum2"))))
     (sgml-ignored-face ((t (:bold t  :foreground "Gray50"))))
     (sgml-ms-end-face ((t (:bold t :foreground "MediumPurple1" ))))
     (sgml-ms-end-tag-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-face ((t (:bold t :foreground "MediumPurple1"))))
     (sgml-ms-start-tag-face ((t (:bold t  :foreground "MediumPurple1"))))
     (sgml-pi-face ((t (:bold t :foreground "lime green"))))
     (sgml-sgml-face ((t ())))
     (sgml-short-ref-face ((t ())))
     (sgml-start-tag-face ((t (:bold t  :foreground "DeepSkyBlue2"))))
     (show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (tool-bar ((t (:background "grey87" ))))
     (trailing-whitespace ((t (:background "red" ))))
     (underline ((t (:underline t ))))
     (variable-pitch ((t ())))
     (xsl-fo-main-face ((t ( :foreground "LightSkyBlue"))))
     (xsl-other-element-face ((t ( :foreground "burlywood2"))))
     (xsl-xslt-alternate-face ((t ( :foreground "SeaGreen2"))))
     (xsl-xslt-main-face ((t ( :foreground "LightSkyBlue"))))))))

(provide 'color-theme-sgml)

;;; color-theme-sgml.el ends here
